backend:
  name: git-gateway
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

publish_mode: simple
locale: "ko"

collections:
  - name: "news"
    label: "소식/이벤트"
    label_singular: "소식"
    description: "소식/이벤트 게시판 글을 관리합니다"
    files:
      - name: "news_json"
        label: "소식 목록 (news.json)"
        file: "assets/data/news.json"
        format: json
        fields:
          - label: "소식 목록"
            name: "entries"
            widget: list
            summary: "{{fields.date}} — {{fields.title}}"
            fields:
              - { label: "ID (자동/고유)", name: "id", widget: "string", hint: "영문/숫자/하이픈으로 고유값. 예: 2025-08-10-sbr-cfp" }
              - { label: "날짜", name: "date", widget: "datetime", format: "YYYY-MM-DD", time_format: false }
              - { label: "제목", name: "title", widget: "string" }
              - { label: "본문", name: "content", widget: "markdown" }
              - label: "첨부파일"
                name: "attachments"
                widget: "list"
                collapsed: true
                fields:
                  - { label: "파일", name: "file", widget: "file" }
                  - { label: "표시 이름(선택)", name: "name", widget: "string", required: false }